INSERT INTO ALUMNO.EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, SALARY,
COMMISION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(EMPLOYEES_SEQ.NEXTVAL, 'PEPITO', 'pgrillo', '555 000 000', TO_CHAR(sysdate, 'DD/Mon/RR'), 'AD_PRES', 22000, null, null, 210);

SELECT EMPLOYEES_SEQ.CURRVAL FROM DIAL;

SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 207;

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID )
VALUES (&DEPARTMENT_ID, '&DEPARTMENT_NAME', &LOCATION);

UPDATE EMPLOYEES 
SET DEPARTMENT_ID = 50
WHERE EMPLOYEE_ID = 113;

DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'Finance';

TRUNCATE TABLE copy_emp;

