
--1
DEFINE EMP_LAST_NAME = '&EMP_LAST_NAME';
SELECT LAST_NAME, HIRE_DATE 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME = '&EMP_LAST_NAME'
)
AND LAST_NAME != '&EMP_LAST_NAME'
;
UNDEFINE LAST_NAME;

--2
SELECT EMPLOYEE_ID, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > (
    SELECT ROUND(AVG(SALARY), 0) 
    FROM EMPLOYEES
)
ORDER BY SALARY ASC;

--3
SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (
    SELECT DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LAST_NAME LIKE '%u%'
);

--4
SELECT 
    E.LAST_NAME, 
    E.DEPARTMENT_ID, 
    E.JOB_ID
FROM 
    EMPLOYEES E
WHERE 
    E.DEPARTMENT_ID IN (
        SELECT D.DEPARTMENT_ID
        FROM DEPARTMENTS D
        WHERE D.LOCATION_ID = 1700
);

--5
SELECT 
    LAST_NAME, 
    SALARY
FROM 
    EMPLOYEES 
WHERE 
    MANAGER_ID IN (
        SELECT EMPLOYEE_ID
        FROM EMPLOYEES
        WHERE LAST_NAME = 'King'
    );

--6
SELECT E.DEPARTMENT_ID, E.LAST_NAME, E.JOB_ID
FROM EMPLOYEES E
WHERE 
    E.DEPARTMENT_ID = (
        SELECT DEPARTMENT_ID
        FROM DEPARTMENTS 
        WHERE DEPARTMENT_NAME = 'Executive'
    )
;

--7
SELECT LAST_NAME 
FROM EMPLOYEES 
WHERE
SALARY > (
    SELECT MAX(SALARY)
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 60
);

--8
SELECT 
    EMPLOYEE_ID, 
    LAST_NAME, 
    SALARY
FROM 
    EMPLOYEES 
WHERE 
    SALARY > (
        SELECT AVG(SALARY)
        FROM EMPLOYEES
    )
AND 
    DEPARTMENT_ID IN (
        SELECT DISTINCT DEPARTMENT_ID
        FROM EMPLOYEES 
        WHERE LAST_NAME LIKE '%u%'
    );