--1
SELECT SYSDATE  FROM DUAL;

--2
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY*1.15, 0) AS "NEW SALARY"
FROM EMPLOYEES;

--3, 4
SELECT EMPLOYEE_ID, LAST_NAME, SALARY, ROUND(SALARY*1.15, 0) AS "NEW SALARY", ((SALARY*1.15)-SALARY) AS INCREASE
FROM EMPLOYEES;

--5.a 
SELECT INITCAP(LAST_NAME) AS NAME, LENGTH(LAST_NAME) AS "Length"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'M%' OR LAST_NAME LIKE 'A%';

--5.b
DEFINE FIRST_LETTER = 'H';

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '&FIRST_LETTER%';

UNDEFINE FIRST_LETTER;

--5.c
DEFINE FIRST_LETTER = 'j';

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE UPPER('&FIRST_LETTER%');

UNDEFINE FIRST_LETTER;

--6
SELECT LAST_NAME, ROUND((SYSDATE-HIRE_DATE)/12) AS "MONTHS_WORKED" 
FROM EMPLOYEES;

--7
SELECT LAST_NAME, LPAD(SALARY, 15, '$') AS SALARY
FROM EMPLOYEES;

--8
SELECT LAST_NAME, RPAD('*', FLOOR(SALARY / 1000), '*') AS SALARIES_IN_ASTERISK
FROM EMPLOYEES
ORDER BY SALARY DESC;

--9
SELECT LAST_NAME, TRUNC((SYSDATE - HIRE_DATE) / 7, 0) AS TENURE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER BY TENURE DESC;
