--1
SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';

--2
SELECT COUNTRY_ID, COUNTRY_NAME
FROM COUNTRIES
MINUS
SELECT DISTINCT C.COUNTRY_ID, C.COUNTRY_NAME
FROM COUNTRIES C
JOIN LOCATIONS L ON C.COUNTRY_ID = L.COUNTRY_ID;

--3
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 50
UNION
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80;

--4
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP'
INTERSECT
SELECT EMPLOYEE_ID, LAST_NAME, JOB_ID, DEPARTMENT_ID, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'Sales'
);

--5
SELECT last_name, department_id, TO_CHAR(NULL) department_name
FROM employees
UNION
SELECT TO_CHAR(NULL), department_id, department_name
FROM departments;

SELECT department_id, last_name, salary
FROM (
    SELECT department_id, last_name, salary, 0 orden
    FROM employees
    UNION
    SELECT department_id, 'Total', SUM(salary), 1
    FROM employees
    GROUP BY department_id
)
ORDER BY 1, orden, 2;