--1
select LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > 12000 ;

--2
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 176 ;

--3
SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000;

--4
SELECT LAST_NAME, JOB_ID, HIRE_DATE
FROM EMPLOYEES
WHERE  last_name IN ('Matos', 'Taylor');

--5
SELECT LAST_NAME, DEPARTMENT_ID
FROM EMPLOYEES
WHERE  department_id = 60 
OR department_id = 80 
ORDER BY LAST_NAME ASC ;

--6
SELECT LAST_NAME as Employee, SALARY as "Monthly Salary", DEPARTMENT_ID
FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 50) 
AND (SALARY BETWEEN 5000 AND 12000);

--7
SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '01/01/10' AND '31/12/10';

--8
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

--9 
SELECT LAST_NAME, SALARY, COMMISSION_PCT
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY, COMMISSION_PCT DESC;

--10
DEFINE EMPLOYEE_SALARY = 1200

select LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > &EMPLOYEE_SALARY;

UNDEFINE EMPLOYEE_SALARY;

--11
DEFINE MANAGER_NUM = 103

select employee_id, last_name, salary, department_id
FROM EMPLOYEES
WHERE MANAGER_ID = &MANAGER_NUM;

UNDEFINE MANAGER_NUM;


