--1. true
--2. false
--3. true
--4. 
SELECT MIN(SALARY) AS MINIMUM, MAX(SALARY) AS MAXIMUM, ROUND(AVG(SALARY),0)
FROM EMPLOYEES;
--5
SELECT JOB_ID, MIN(SALARY) AS MINIMUM, MAX(SALARY) AS MAXIMUM, ROUND(AVG(SALARY),0)
FROM EMPLOYEES
GROUP BY JOB_ID;
--6
SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
WHERE JOB_ID = '&JOB_ID'
GROUP BY JOB_ID;

UNDEFINE JOB_ID;

--7
SELECT COUNT(*) AS "NUMBER OF MANAGERS"
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

--8
SELECT (MAX(SALARY) - MIN(SALARY)) AS "DIFERENCE"
FROM EMPLOYEES;

--9
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MIN(SALARY) < 6000;

--10

--11 (METODO 1)
SELECT 
    JOB_ID,
    SUM(CASE WHEN DEPARTMENT_ID = 20 THEN SALARY ELSE NULL END) AS DEPT_20_SALARY,
    SUM(CASE WHEN DEPARTMENT_ID = 50 THEN SALARY ELSE NULL END) AS DEPT_50_SALARY,
    SUM(CASE WHEN DEPARTMENT_ID = 80 THEN SALARY ELSE NULL END) AS DEPT_80_SALARY,
    SUM(CASE WHEN DEPARTMENT_ID = 90 THEN SALARY ELSE NULL END) AS DEPT_90_SALARY,
    SUM(SALARY) AS TOTAL_SALARY
FROM 
    EMPLOYEES
GROUP BY 
    JOB_ID
ORDER BY 
    JOB_ID;

--1 (METODO 2)
SELECT
        JOB_ID AS "Job",
        SUM(DECODE(DEPARTMENT_ID,20,SALARY)) AS "Dept 20",
        SUM(DECODE(DEPARTMENT_ID,50,SALARY)) AS "Dept 50",
        SUM(DECODE(DEPARTMENT_ID,80,SALARY)) AS "Dept 80",
        SUM(DECODE(DEPARTMENT_ID,90,SALARY)) AS "Dept 90",
        SUM(SALARY) AS "Total"
 
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20,50,80,90)
GROUP BY JOB_ID;