--1
SELECT LAST_NAME || ' EARNS ' || SALARY || ' MONTHLY BUT WANTS ' || (SALARY * 3) AS DREAM_SALARIES
FROM EMPLOYEES;

--2
SELECT LAST_NAME, HIRE_DATE, TO_CHAR(NEXT_DAY(ADD_MONTHS(HIRE_DATE, 6), 'MONDAY'), 'FMDay, "the" Ddspth "of" Month, YYYY') AS REVIEW
FROM EMPLOYEES;
--3
SELECT LAST_NAME, 
CASE 
    WHEN COMMISSION_PCT IS NULL THEN 'no commission'
    ELSE TO_CHAR(COMMISSION_PCT)
    END AS COMM
FROM 
    EMPLOYEES;
--4
SELECT LAST_NAME, JOB_ID, 
CASE JOB_ID WHEN 'AD_PRES' THEN 'A'
            WHEN 'ST_MAN' THEN 'B'
            WHEN 'IT_PROG' THEN 'C'
            WHEN 'SA_REP' THEN 'D'
            WHEN 'ST_CLERK' THEN 'E'
ELSE '0' END "GRADE"
FROM EMPLOYEES;

--5
SELECT LAST_NAME, JOB_ID, 
(CASE WHEN JOB_ID ='AD_PRES' THEN 'A'
      WHEN JOB_ID ='ST_MAN' THEN 'B'
      WHEN JOB_ID ='IT_PROG' THEN 'C'
      WHEN JOB_ID ='SA_REP' THEN 'D'
      WHEN JOB_ID ='ST_CLERK' THEN 'E'
ELSE '0' END) "GRADE"
FROM EMPLOYEES;

--6
SELECT LAST_NAME, JOB_ID, 
DECODE(JOB_ID, 'AD_PRES', 'A',
            'ST_MAN','B',
            'IT_PROG', 'C',
           'SA_REP', 'D',
            'ST_CLERK' , 'E',
            'None of the above')
FROM EMPLOYEES;

